#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: curtomil (crtml)

# Short bio or description (displayed in the header)
description: Socia(l / ble) Scientist

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://pbs.twimg.com/profile_images/1650831321/hawat81_gmail.com_fa07d7a3_400x400.jpg

source: .
destination: ./_site
exclude: node_modules
port: 4000
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: curtomil
  instagram: 
  linkedin: 
  pinterest: 
  rss: blog # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: curtomil
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://curtomil.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: css/_scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - ./_plugins/reading_time
  - jekyll-scholar

# Scholar configuration
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference }}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - js-yaml